[package]
name = "fincore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
libc = { workspace = true }
memmap2 = { workspace = true }
tabled = "0.16.0"
